name: Build and Compile Firmware

description: |
  This workflow automates the compilation and build process for Arduino Nano, ESP8266 and ESP32 using PlatformIO.

on:
  push:
    branches:
      - main  # Trigger build on push to main branch
      - Development
  pull_request:
    branches:
      - main  # Trigger build on pull requests to main branch
      - Development
jobs:
  
  #############################[NANO]######################################################
  build_nano:
    name: Compile Firmware for Arduino Nano
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the latest code from the repository

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio  # Install PlatformIO CLI

      - name: Build Firmware for Arduino Nano
        run: pio run -e nano  # Compile the firmware for Arduino Nano

      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v4  # Upload the compiled firmware as an artifact
        with:
          name: firmware-nano
          path: .pio/build/nano/firmware.*  # Path to the compiled firmware

  #############################[UNO]######################################################
  build_uno:
    name: Compile Firmware for Arduino Uno
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the latest code from the repository

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio  # Install PlatformIO CLI

      - name: Build Firmware for Arduino Uno
        run: pio run -e uno  # Compile the firmware for Arduino Nano

      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v4  # Upload the compiled firmware as an artifact
        with:
          name: firmware-uno
          path: .pio/build/uno/firmware.*  # Path to the compiled firmware


  ############################[ESP8266]#####################################################
  build_esp8266:
    name: Compile Firmware for ESP8266
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the latest code from the repository

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio  # Install PlatformIO CLI

      - name: Build Firmware for ESP8266
        run: pio run -e esp8266  # Compile the firmware for ESP8266 (Use esp12e environment name)

      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v4  # Upload the compiled firmware as an artifact
        with:
          name: firmware-esp8266
          path: .pio/build/esp8266/firmware.*  # Path to the compiled firmware


  ##############################[ESP32]#####################################################
  build_esp32:
    name: Compile Firmware for ESP32
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the latest code from the repository

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio  # Install PlatformIO CLI

      - name: Build Firmware for ESP32
        run: pio run -e esp32  # Compile the firmware for ESP32

      - name: Upload Compiled Firmware
        uses: actions/upload-artifact@v4  # Upload the compiled firmware as an artifact
        with:
          name: firmware-esp32
          path: .pio/build/esp32/firmware.*  # Path to the compiled firmware    